import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserContext from "./contexts/UserContext";
import {UserProtectWrapper} from "./UserProtectWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Use `pathname` from `next/router` to determine protected routes
  const protectedRoutes = ["/home"];
  const isProtected = typeof window !== "undefined" && protectedRoutes.includes(window.location.pathname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserContext>
          {isProtected ? (
            <UserProtectWrapper>
              {children}
            </UserProtectWrapper>
          ) : (
            children
          )}
        </UserContext>
      </body>
    </html>
  );
}
